/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: '#0A7CFF',
        secondary: '#22C55E',
        danger: '#EF4444',
        warning: '#F59E0B',
        success: '#10B981',
        info: '#0A7CFF',
        'text-primary': '#1F2937',
        'text-secondary': '#6B7280',
        'text-muted': '#94A3B8',
        'app-border': '#E2E8F0',
        surface: '#FFFFFF',
        background: '#F8FAFC',
        'background-light': '#F8FAFC',
        'background-dark': '#18181B',
        'surface-light': '#FFFFFF',
        'surface-dark': '#27272A',
        'text-light': '#1F2937',
        'text-dark': '#E5E7EB',
        'border-light': '#E2E8F0',
        'border-dark': '#3F3F46',
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        md: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['22px', { lineHeight: '32px' }],
        xxl: ['28px', { lineHeight: '36px' }],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '20px',
        xxl: '24px',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
      },
    },
  },
  plugins: [],
}
